import { test, expect } from "@playwright/test";
const data = {
    "vacuum-drop": { answer: "They land together", bad: "Mass causes acceleration.", teach: "In vacuum both objects have the same acceleration independent of mass.", transfer: "They have the same acceleration and land together", why: "They have the same acceleration in a vacuum." },
    "collision-forces": { answer: "Equal magnitude, opposite directions", bad: "The truck has more mass so it exerts more force.", teach: "The vehicles exert equal and opposite forces.", transfer: "Wall and cyclist exert equal and opposite forces", why: "They exert equal and opposite forces during contact." },
    "projectile-motion": { answer: "No horizontal force is required", bad: "A forward force continues after release.", teach: "There is zero horizontal acceleration and gravity acts vertically.", transfer: "Zero horizontal acceleration; gravity acts vertically", why: "There is zero horizontal acceleration and gravity acts vertically." }
};
async function complete(page, id) { const d = data[id]; await page.goto(`/learn/${id}`); await page.getByLabel(d.answer).check(); await page.getByRole("button", { name: "Explain your method" }).click(); await page.getByLabel("Reasoning").fill(d.bad); await page.getByRole("button", { name: "Map reasoning" }).click(); await expect(page.getByText("Cached analysis, live validation")).toBeVisible(); await page.getByRole("button", { name: "Make prediction" }).click(); await page.getByLabel(d.answer).check(); await page.getByRole("button", { name: "Unlock simulation" }).click(); await page.getByRole("button", { name: "Run simulation" }).click(); await expect(page.getByText("Observed result")).toBeVisible(); await page.getByRole("button", { name: "Explain again" }).click(); await page.getByLabel("Revised reasoning").fill(d.teach); await page.getByRole("button", { name: "Verify repair" }).click(); await expect(page.getByText("Required relations mapped.")).toBeVisible(); await page.getByRole("button", { name: "Test transfer" }).click(); await page.getByLabel(d.transfer).check(); await page.getByLabel("Why?").fill(d.why); await page.getByRole("button", { name: "Verify transfer" }).click(); await expect(page.getByText("Method repaired. Transfer verified.")).toBeVisible(); }
for (const id of Object.keys(data))
    test(`complete ${id} production flow`, async ({ page }) => complete(page, id));
test("failed repair and transfer remain incomplete", async ({ page }) => { await page.goto("/learn/vacuum-drop"); await page.getByLabel("They land together").check(); await page.getByRole("button", { name: "Explain your method" }).click(); await page.getByLabel("Reasoning").fill("Mass causes acceleration."); await page.getByRole("button", { name: "Map reasoning" }).click(); await page.getByRole("button", { name: "Make prediction" }).click(); await page.getByLabel("They land together").check(); await page.getByRole("button", { name: "Unlock simulation" }).click(); await page.getByRole("button", { name: "Run simulation" }).click(); await page.getByRole("button", { name: "Explain again" }).click(); await page.getByLabel("Revised reasoning").fill("I still think mass matters."); await page.getByRole("button", { name: "Verify repair" }).click(); await expect(page.getByText("One relationship still needs revision.")).toBeVisible(); });
test("vacuum gold path succeeds ten consecutive times", async ({ page }) => { for (let run = 0; run < 10; run++) {
    await complete(page, "vacuum-drop");
    await expect(page.getByText("Method repaired. Transfer verified.")).toBeVisible();
} });
