import { z } from "zod";

export const RelationSchema = z.enum(["causes", "equal_to", "opposes", "has_acceleration", "has_no_acceleration"]);
export const PackSchema = z.object({
  id: z.enum(["vacuum-drop", "collision-forces", "projectile-motion"]), title: z.string(), shortTitle: z.string(), problem: z.string(), choices: z.array(z.object({ id: z.string(), label: z.string() })).min(2), correctAnswer: z.string(),
  concepts: z.array(z.object({ id: z.string(), label: z.string() })).min(4), required: z.array(z.object({ source: z.string(), target: z.string(), type: RelationSchema })), forbidden: z.array(z.object({ source: z.string(), target: z.string(), type: RelationSchema })),
  misconception: z.string(), diagnostic: z.string(), prediction: z.string(), observation: z.string(), transfer: z.object({ question: z.string(), choices: z.array(z.object({ id: z.string(), label: z.string() })), correctAnswer: z.string() }), facts: z.array(z.string()), citation: z.string()
});
export type Pack = z.infer<typeof PackSchema>;
const packs: Pack[] = [
 { id:"vacuum-drop", title:"Vacuum Drop", shortTitle:"Drop", problem:"A 1 kg steel sphere and a 10 kg steel sphere are released together from 20 m inside a vacuum chamber. Which lands first?", choices:[{id:"same",label:"They land together"},{id:"heavy",label:"The 10 kg sphere lands first"},{id:"light",label:"The 1 kg sphere lands first"}], correctAnswer:"same", concepts:[{id:"mass",label:"Mass"},{id:"gravity",label:"Gravity"},{id:"force",label:"Gravitational force"},{id:"acceleration",label:"Free-fall acceleration"},{id:"landing",label:"Landing time"}], required:[{source:"gravity",target:"acceleration",type:"causes"},{source:"mass",target:"force",type:"causes"},{source:"force",target:"acceleration",type:"causes"},{source:"acceleration",target:"landing",type:"causes"}], forbidden:[{source:"mass",target:"acceleration",type:"causes"}], misconception:"Greater mass causes greater free-fall acceleration.", diagnostic:"In a vacuum, would changing only mass change gravitational acceleration? Why?", prediction:"Before running the vacuum test, predict the result.", observation:"Both objects reach the floor at 2.02 s. In a vacuum their acceleration is g, independent of mass.", transfer:{question:"On the Moon, a 2 kg tool and 8 kg tool fall from the same height in a vacuum. What is true?",choices:[{id:"same",label:"They have the same acceleration and land together"},{id:"heavy",label:"The 8 kg tool accelerates more"},{id:"damage",label:"They cause equal damage"}],correctAnswer:"same"}, facts:["t = √(2h/g)","Vacuum removes air resistance; it does not describe every real-world fall."], citation:"OpenStax, University Physics Vol. 1, §5.5" },
 { id:"collision-forces", title:"Collision Forces", shortTitle:"Collision", problem:"A truck collides head-on with a compact car. During contact, which force is larger?", choices:[{id:"equal",label:"Equal magnitude, opposite directions"},{id:"truck",label:"Truck on car is larger"},{id:"car",label:"Car on truck is larger"}],correctAnswer:"equal", concepts:[{id:"truck",label:"Truck"},{id:"car",label:"Car"},{id:"truckForce",label:"Force on truck"},{id:"carForce",label:"Force on car"},{id:"acceleration",label:"Acceleration"}],required:[{source:"truckForce",target:"carForce",type:"equal_to"},{source:"truckForce",target:"carForce",type:"opposes"},{source:"carForce",target:"acceleration",type:"causes"}],forbidden:[{source:"truck",target:"carForce",type:"causes"}],misconception:"A truck exerts more force on a car than the car exerts on the truck.",diagnostic:"If the forces are a third-law pair, what is their relationship?",prediction:"Predict the two contact-force arrows.",observation:"The arrows are equal in magnitude and opposite in direction. Different masses can still have different accelerations and damage.",transfer:{question:"A cyclist hits a wall. During the instant of contact, which statement is correct?",choices:[{id:"equal",label:"Wall and cyclist exert equal and opposite forces"},{id:"wall",label:"The wall exerts more force"},{id:"damage",label:"Equal force means equal damage"}],correctAnswer:"equal"},facts:["Newton's third law pairs act on different objects.","Equal force does not imply equal acceleration or damage."],citation:"OpenStax, University Physics Vol. 1, §4.4" },
 { id:"projectile-motion",title:"Projectile Motion",shortTitle:"Projectile",problem:"A ball rolls off a level table after being pushed. After release, what horizontal force keeps it moving forward in the idealized model?",choices:[{id:"none",label:"No horizontal force is required"},{id:"forward",label:"A continuing forward force"},{id:"gravity",label:"Gravity pushes it forward"}],correctAnswer:"none",concepts:[{id:"release",label:"Release"},{id:"horizontalForce",label:"Horizontal force"},{id:"horizontalAcceleration",label:"Horizontal acceleration"},{id:"gravity",label:"Gravity"},{id:"verticalAcceleration",label:"Vertical acceleration"}],required:[{source:"release",target:"horizontalAcceleration",type:"has_no_acceleration"},{source:"gravity",target:"verticalAcceleration",type:"causes"}],forbidden:[{source:"horizontalForce",target:"horizontalAcceleration",type:"causes"}],misconception:"A forward force continues acting on a projectile after release.",diagnostic:"After release, what causes the horizontal acceleration in the idealized model?",prediction:"Predict the post-release force and path.",observation:"The idealized path is parabolic: horizontal acceleration is 0 and vertical acceleration is g downward.",transfer:{question:"A puck leaves a frictionless ramp moving horizontally. Which model applies after it leaves?",choices:[{id:"none",label:"Zero horizontal acceleration; gravity acts vertically"},{id:"forward",label:"A forward force maintains its speed"},{id:"stop",label:"It immediately stops"}],correctAnswer:"none"},facts:["Ideal model: ignore air resistance.","aₓ = 0; aᵧ = −g after release."],citation:"OpenStax, University Physics Vol. 1, §5.3" }
];
export const PACKS = packs.map((p) => PackSchema.parse(p));
export const getPack = (id: string) => PACKS.find((pack) => pack.id === id);
export const publicPack = (pack: Pack) => ({...pack, forbidden: undefined, required: undefined, misconception: undefined});
