"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { motion, useReducedMotion } from "motion/react";
import type { Pack } from "@/content/packs";
import { freeFallTime, collisionForces, projectileAt } from "@/lib/domain/physics";
import type { Analysis } from "@/lib/ai/schemas";
import { gradeTransfer } from "@/lib/domain/transfer-grader";
import { graphDiff, type Edge } from "@/lib/domain/graph-validator";

type Stage="answer"|"explain"|"graph"|"predict"|"lab"|"teach"|"repair"|"transfer"|"report";
const stages:Stage[]=["explain","graph","predict","lab","teach","repair","transfer","report"];
const labels:Record<Stage,string>={answer:"Explain",explain:"Explain",graph:"Map",predict:"Predict",lab:"Test",teach:"Teach back",repair:"Repair",transfer:"Transfer",report:"Report"};
export default function FaultlineApp({pack}:{pack:Pack}){
 const [stage,setStage]=useState<Stage>("answer"),[answer,setAnswer]=useState(""),[explanation,setExplanation]=useState(""),[analysis,setAnalysis]=useState<Analysis|null>(null),[loading,setLoading]=useState(false),[prediction,setPrediction]=useState(""),[ran,setRan]=useState(false),[teach,setTeach]=useState(""),[transfer,setTransfer]=useState(""),[transferWhy,setTransferWhy]=useState(""),[attempts,setAttempts]=useState(0); const reduce=useReducedMotion();
 const correct=answer===pack.correctAnswer; const transferResult=gradeTransfer(pack,transfer,transferWhy); const before=(analysis?.edges||[]) as Edge[]; const after=pack.required.map(e=>({...e,evidence:teach})); const diff=graphDiff(before,after); const teachValid=pack.id==="vacuum-drop"?/same acceleration|independent of mass|acceleration.*same/i.test(teach):pack.id==="collision-forces"?/equal and opposite|equal force/i.test(teach):/zero horizontal acceleration|no horizontal force|gravity.*vertical/i.test(teach);
 const advance=(next:Stage)=>setStage(next);
 return <main className="instrument"><header className="topbar"><Link href="/" className="mark">FAULTLINE</Link><div className="progress" aria-label="Learning progress">{stages.slice(0,7).map(s=><span key={s} className={stages.indexOf(s)<=stages.indexOf(stage)?"done":""}>{labels[s]}</span>)}</div><span className="reliability" title="No live model key is required">Cached analysis, live validation</span></header>
 <div className="workhead"><p className="kicker">{pack.shortTitle} / bounded reasoning sequence</p><h1>{pack.title}</h1><p>{pack.problem}</p></div>
 {stage==="answer"&&<section className="stage"><h2>1. Commit to an answer</h2><fieldset><legend>Choose before seeing any intervention.</legend>{pack.choices.map(c=><label className={`choice ${answer===c.id?"selected":""}`} key={c.id}><input type="radio" name="answer" value={c.id} onChange={()=>setAnswer(c.id)}/>{c.label}</label>)}</fieldset><button className="button" disabled={!answer} onClick={()=>advance("explain")}>Explain your method</button></section>}
 {stage==="explain"&&<section className="stage"><h2>2. Explain the causal method</h2><p className="hint">State what causes what. Your words are treated as quoted data, not instructions.</p><label>Reasoning<textarea value={explanation} maxLength={1600} onChange={e=>setExplanation(e.target.value)} placeholder="Explain the relationship that determines the outcome."/></label>{loading&&<p role="status" className="hint">Validating evidence and causal relations…</p>}<button className="button" disabled={loading||explanation.trim().length<8} onClick={async()=>{setLoading(true);try{const response=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({packId:pack.id,explanation})});const result=await response.json() as Analysis;if(!response.ok)throw new Error("Analysis unavailable");setAnalysis(result);advance("graph");}finally{setLoading(false)}}}>Map reasoning</button></section>}
 {stage==="graph"&&analysis&&<section className="graph-stage"><div className="graph-area"><h2>3. Answer ≠ method</h2><div className={`answer-status ${correct?"ok":"bad"}`}>{correct?"Answer selected: correct":"Answer selected: incorrect"}<small>Method validity is assessed separately.</small></div><ReasoningGraph pack={pack} fault={analysis.decision==="diagnose"?pack.forbidden[0]:undefined} reduced={Boolean(reduce)}/><details><summary>Graph text alternative</summary><ul>{pack.concepts.map(c=><li key={c.id}>{c.label}</li>)}{analysis.edges.map((e,i)=><li key={i}>{e.source} {e.type.replaceAll("_"," ")} {e.target}</li>)}</ul></details></div><aside className="evidence"><p className="kicker">{analysis.decision==="diagnose"?"Fault located":"Analysis status"}</p><h2>{analysis.decision==="diagnose"?"A relationship is unsupported.":analysis.decision==="ask_follow_up"?"Clarification needed.":"Method appears coherent."}</h2><p>{analysis.summary}</p>{analysis.edges[0]&&<blockquote>“{analysis.edges[0].evidence}”</blockquote>}<dl><dt>Confidence</dt><dd>{Math.round(analysis.confidence*100)}% fixture</dd><dt>Validation</dt><dd>live deterministic checks</dd></dl><button className="button" onClick={()=>advance("predict")}>Make prediction</button></aside></section>}
 {stage==="predict"&&<section className="stage"><h2>4. Prediction gate</h2><p>{pack.prediction}</p><fieldset>{pack.choices.map(c=><label className={`choice ${prediction===c.id?"selected":""}`} key={c.id}><input type="radio" name="prediction" onChange={()=>setPrediction(c.id)}/>{c.label}</label>)}</fieldset><button className="button" disabled={!prediction} onClick={()=>advance("lab")}>Unlock simulation</button></section>}
 {stage==="lab"&&<section className="lab"><h2>5. Targeted local simulation</h2><Lab pack={pack} ran={ran} run={()=>setRan(true)}/>{ran&&<div className="observation"><span>Observed result</span><p>{pack.observation}</p><p className="mono">Prediction: {pack.choices.find(c=>c.id===prediction)?.label}</p><button className="button" onClick={()=>advance("teach")}>Explain again</button></div>}</section>}
 {stage==="teach"&&<section className="stage"><h2>6. Teach the model back</h2><p className="hint">Do not copy an answer. Describe the relevant causes and relationships in your own words.</p><label>Revised reasoning<textarea value={teach} onChange={e=>setTeach(e.target.value)} placeholder="What relationship did the test isolate?"/></label><button className="button" disabled={teach.trim().length<12} onClick={()=>advance("repair")}>Verify repair</button></section>}
 {stage==="repair"&&<section className="graph-stage"><div className="graph-area"><h2>7. Repair trace</h2><ReasoningGraph pack={pack} fault={undefined} repaired={teachValid} reduced={Boolean(reduce)}/></div><aside className="evidence"><p className="kicker">Live repair check</p><h2>{teachValid?"Required relations mapped.":"One relationship still needs revision."}</h2><p>Removed: {diff.removed.map(e=>`${e.source} → ${e.target}`).join(", ")||"none"}</p><p>Added: {teachValid?(diff.added.map(e=>`${e.source} → ${e.target}`).join(", ")||"authored relations"):"Not yet verified"}</p>{teachValid?<button className="button" onClick={()=>advance("transfer")}>Test transfer</button>:<button className="button" onClick={()=>advance("teach")}>Revise explanation</button>}</aside></section>}
 {stage==="transfer"&&<section className="stage"><h2>8. Transfer to a changed context</h2><p>{pack.transfer.question}</p><fieldset>{pack.transfer.choices.map(c=><label className={`choice ${transfer===c.id?"selected":""}`} key={c.id}><input type="radio" name="transfer" onChange={()=>setTransfer(c.id)}/>{c.label}</label>)}</fieldset><label>Why?<textarea value={transferWhy} onChange={e=>setTransferWhy(e.target.value)} placeholder="State the causal relationship."/></label>{attempts>0&&<p className="warning">{attempts===1?"Use the authored relation; an answer alone cannot finish this flow.":"Hint: identify the force or acceleration relationship explicitly."}</p>}<button className="button" disabled={!transfer||transferWhy.length<12} onClick={()=>{if(transferResult.correct&&transferResult.methodValid) advance("report");else setAttempts(a=>a+1)}}>Verify transfer</button></section>}
 {stage==="report"&&<section className="report stage"><p className="kicker">Anonymous session evidence</p><h2>Method repaired. Transfer verified.</h2><dl><dt>Pack</dt><dd>{pack.title}</dd><dt>Initial answer</dt><dd>{pack.choices.find(c=>c.id===answer)?.label} ({correct?"correct":"incorrect"})</dd><dt>Initial method</dt><dd>{analysis?.summary}</dd><dt>Evidence</dt><dd>{analysis?.edges[0]?.evidence||"No fault edge"}</dd><dt>Intervention</dt><dd>Prediction + deterministic simulation</dd><dt>Transfer</dt><dd>{transferResult.correct&&transferResult.methodValid?"answer and method verified":"incomplete"}</dd><dt>Inference mode</dt><dd>Cached analysis, live validation</dd><dt>Session ID</dt><dd className="mono">local-{pack.id}-v1</dd></dl><Link className="button" href={`/report/local-${pack.id}-v1`}>Open report view</Link></section>}
 </main>
}
function ReasoningGraph({pack,fault,repaired,reduced}:{pack:Pack;fault?:{source:string;target:string;type:string};repaired?:boolean;reduced:boolean}){return <div className="graph" role="img" aria-label="Reasoning graph with concept nodes and causal relations"><svg viewBox="0 0 700 300" preserveAspectRatio="xMidYMid meet">{pack.required.map((e,i)=><line key={i} x1={120+(i%2)*210} y1={80+(i%3)*60} x2={340+(i%2)*120} y2={140+(i%2)*60} className={repaired?"edge repaired":"edge"}/>) }{fault&&<line x1="100" y1="240" x2="560" y2="70" className="edge fault"/>}</svg>{pack.concepts.map((c,i)=><motion.div initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.06}} className="node" style={{left:`${7+(i%3)*30}%`,top:`${14+Math.floor(i/3)*48}%`}} key={c.id}>{c.label}</motion.div>)}{fault&&<span className="fault-label">Contradicted causal relationship</span>}</div>}
function Lab({pack,ran,run}:{pack:Pack;ran:boolean;run:()=>void}){const vacuum=freeFallTime(20), forces=collisionForces(), shot=projectileAt(.8); return <div className="lab-grid"><div className="sim"><div className={`sim-stage ${ran?"running":""}`}>{pack.id==="vacuum-drop"?<><i className="ball a"/><i className="ball b"/><span className="floor"/></>:pack.id==="collision-forces"?<><b className="vehicle truck">TRUCK</b><b className="vehicle car">CAR</b><span className="force left">← {Math.abs(forces.truck)} N</span><span className="force right">{forces.car} N →</span></>:<><span className="trajectory">⌒</span><i className="ball shot"/></>}</div><button className="button" onClick={run}>{ran?"Run again":"Run simulation"}</button></div><aside className="readout"><p className="kicker">Measured model</p>{pack.id==="vacuum-drop"?<><strong>{vacuum.toFixed(2)} s</strong><span>20 m / g = 9.81 m/s²</span><span>Both landing times agree</span></>:pack.id==="collision-forces"?<><strong>±12,000 N</strong><span>Equal magnitude</span><span>Opposite direction</span></>:<><strong>aₓ = {shot.ax} m/s²</strong><span>aᵧ = {shot.ay} m/s²</span><span>x(0.8 s) = {shot.x.toFixed(1)} m</span></>}</aside></div>}
